name: codehub_platform
description: "CodeHub is an e-learning platform that offers video lectures and comprehensive notes for a wide range of programming languages."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.jpeg"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/android_dev_img.jpeg
    - assets/images/backend_img.png
    - assets/images/c++_img.png
    - assets/images/DSA.webp
    - assets/images/dbms_img.jpg
    - assets/images/flutter_img.png
    - assets/images/frontend_img.jpeg
    - assets/images/Java_img.jpeg
    - assets/images/linear_DSA.png
    - assets/images/nonlinear_DSA.webp
    - assets/images/oops_img.jpg
    - assets/images/os_img.png
    - assets/images/python_img.webp
    - assets/images/react_native_img.jpg
    - assets/images/fullstack_img.png
    - assets/images/cn_img.png
    - assets/images/app_logo.jpeg
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
